---
net_config:
  ip_base: "10.10.5.0"
  netmask: 12
  gateway: "10.0.0.1"

#Proxmox VM config defaults
node_config:
  control_plane:
    node_count: 1
    ip_offset: 90
    name_prefix: "kube-control-0"
    target_node: "UditSuperServer"
    vmid_prefix: "80"
    agent: 1
    cores: 8
    sockets: 1
    cpu: "host"
    memory: 8192
    scsihw: "virtio-scsi-single"
    bootdisk: "scsi0"
    disk:
      slot: 0
      size: "20G"
      type: "scsi"
      storage: "local-zfs-nvme-1"
      iothread: 1
    network:
      model: "virtio"
      bridge: "vmbr0"

    #Proxmox VM config defaults
  worker:
    node_count: 0
    ip_offset: 90
    name_prefix: "kube-worker-0"
    target_node: "UditSuperServer"
    vmid_prefix: "50"
    agent: 1
    cores: 4
    sockets: 1
    cpu: "host"
    memory: 8192
    scsihw: "virtio-scsi-single"
    bootdisk: "scsi0"
    disk:
      slot: 0
      size: "10G"
      type: "scsi"
      storage: "local-zfs"
      iothread: 1
    network:
      model: "virtio"
      bridge: "vmbr0"

    #Proxmox VM config defaults
  gpu:
    node_count: 0
    ip_offset: 90
    name_prefix: "kube-gpu-node-0"
    target_node: "UditSuperServer"
    vmid_prefix: "80"
    agent: 1
    cores: 4
    sockets: 1
    cpu: "host"
    memory: 8192
    scsihw: "virtio-scsi-single"
    bootdisk: "scsi0"
    disk:
      slot: 0
      size: "10G"
      type: "scsi"
      storage: "local-zfs"
      iothread: 1
    network:
      model: "virtio"
      bridge: "vmbr0"
